language: node_js
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
    - ~/.npm
notifications:
  email: false
node_js:
  - '9'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - npm i -g makeshift && makeshift -s @bcoe -r https://registry.npmjs.org
script:
  - yarn run build
after_success:
  - yarn deploy-docs

deploy:
  provider: npm
  email: ben@npmjs.com
  api_key: $NPM_TOKEN
  on:
    tags: true


