language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
script:
  - yarn run build
after_success:
  - yarn deploy-docs
  - yarn semantic-release

